//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotDogDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int pk_id { get; set; }
        public string itemName { get; set; }
        public double itemPrice { get; set; }
        public int fk_itemType { get; set; }
    
        public virtual ItemType ItemType { get; set; }
    }
}
